first step toward not removing everything from /dev on umount fail

diff --git a/lib/common-functions b/lib/common-functions
--- a/lib/common-functions
+++ b/lib/common-functions
@@ -14,6 +14,34 @@
 # License for the specific language governing permissions and limitations
 # under the License.
 
+function safe_umount(){
+  MAX_RETRIES=4
+  TIME_TO_SLEEP=10
+
+  umount_target=$1
+  counter=1
+  set +e
+  while true; do
+    sync
+    umount $umount_target
+
+    if [ $? -ne 0 ]; then
+      sleep $TIME_TO_SLEEP
+      counter=$[$counter +1]
+    else
+      break
+    fi
+
+    if [ "$counter" -gt "$MAX_RETRIES" ]; then
+      echo "failed to umount ${umount_target}"
+      exit 1
+    fi
+
+  done
+
+  set -e
+}
+
 function tmpfs_check() {
   [ "$DIB_NO_TMPFS" == "0" ] || return 1
   [ -r /proc/meminfo ] || return 1
@@ -128,7 +156,7 @@ function map_nbd {
 
 # Delete and unmount the working dir used in extracting kernel/initrd
 function unmount_qcow_image () {
-    sudo umount $WORK_DIR || true
+    safe_umount $WORK_DIR
     sudo qemu-nbd -d $NBD_DEV || true
     sudo rm -rf $WORK_DIR
 
@@ -150,7 +178,7 @@ function mount_qcow_image() {
 function cleanup_dirs () {
     sudo rm -rf $TMP_BUILD_DIR/built
     sudo rm -rf $TMP_BUILD_DIR/mnt
-    sudo umount -f  $TMP_BUILD_DIR || true
+    safe_umount $TMP_BUILD_DIR
     rm -rf $TMP_BUILD_DIR
 }
 
diff --git a/lib/img-functions b/lib/img-functions
--- a/lib/img-functions
+++ b/lib/img-functions
@@ -13,6 +13,45 @@
 # License for the specific language governing permissions and limitations
 # under the License.
 
+# SCRIPTNAME=$(basename $0)
+# SCRIPT_HOME=$(dirname $0)
+# if [ -d $SCRIPT_HOME/../share/diskimage-builder ]
+# then
+#     export _PREFIX=$SCRIPT_HOME/../share/diskimage-builder
+# else
+#     export _PREFIX=$SCRIPT_HOME/..
+# fi
+# export _LIB=$_PREFIX/lib
+# source $_LIB/common-functions
+
+function safe_umount(){
+  MAX_RETRIES=4
+  TIME_TO_SLEEP=10
+
+  umount_target=$1
+  counter=1
+  set +e
+  while true; do
+    sync
+    umount $umount_target
+
+    if [ $? -ne 0 ]; then
+      sleep $TIME_TO_SLEEP
+      counter=$[$counter +1]
+    else
+      break
+    fi
+
+    if [ "$counter" -gt "$MAX_RETRIES" ]; then
+      echo "failed to umount ${umount_target}"
+      exit 1
+    fi
+
+  done
+
+  set -e
+}
+
 function unmount_image () {
     # Calling sync before helps ensure the mount isn't busy when you unmount it.
     # Previously observing having disk corruption issues; one possibility is
@@ -25,7 +64,7 @@ function unmount_image () {
     local MOUNTS
     MOUNTS=$(grep < /proc/mounts " $TMP_BUILD_DIR/mnt" | awk '{ print $2 }' | sort -r)
     for M in $MOUNTS; do
-        sudo umount -f $M || true
+        safe_umount $M
     done
     if [ -n "$EXTRA_UNMOUNT" ]; then
         $EXTRA_UNMOUNT
@@ -83,7 +122,7 @@ function run_d_in_target () {
       run_in_target dib-run-parts /tmp/in_target.d/$1.d
       trap - ERR
       check_break after-$1 run_in_target bash
-      sudo umount -f $TMP_MOUNT_PATH/tmp/in_target.d
+      safe_umount $TMP_MOUNT_PATH/tmp/in_target.d
       sudo rmdir $TMP_MOUNT_PATH/tmp/in_target.d
     fi
 }
diff --git a/lib/ramdisk-functions b/lib/ramdisk-functions
--- a/lib/ramdisk-functions
+++ b/lib/ramdisk-functions
@@ -15,6 +15,46 @@
 # License for the specific language governing permissions and limitations
 # under the License.
 
+
+# SCRIPTNAME=$(basename $0)
+# SCRIPT_HOME=$(dirname $0)
+# if [ -d $SCRIPT_HOME/../share/diskimage-builder ]
+# then
+#     export _PREFIX=$SCRIPT_HOME/../share/diskimage-builder
+# else
+#     export _PREFIX=$SCRIPT_HOME/..
+# fi
+# export _LIB=$_PREFIX/lib
+# source $_LIB/common-functions
+
+function safe_umount(){
+  MAX_RETRIES=4
+  TIME_TO_SLEEP=10
+
+  umount_target=$1
+  counter=1
+  set +e
+  while true; do
+    sync
+    umount $umount_target
+
+    if [ $? -ne 0 ]; then
+      sleep $TIME_TO_SLEEP
+      counter=$[$counter +1]
+    else
+      break
+    fi
+
+    if [ "$counter" -gt "$MAX_RETRIES" ]; then
+      echo "failed to umount ${umount_target}"
+      exit 1
+    fi
+
+  done
+
+  set -e
+}
+
 function fullpath() {
   local f=$1
   if [ "${f#/}" = "$f" ]; then
@@ -25,7 +65,7 @@ function fullpath() {
 }
 
 function cleanup () {
-  sudo umount -f $TMP_BUILD_DIR || true
+  safe_umount $TMP_BUILD_DIR
   rm -rf --one-file-system "$TMP_BUILD_DIR"
 }
 
